// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type cpuCpuStat struct {
	BusyNs uint64
	IdleNs uint64
	LastTs uint64
	IsBusy uint32
	_      [4]byte
}

// loadCpu returns the embedded CollectionSpec for cpu.
func loadCpu() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CpuBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cpu: %w", err)
	}

	return spec, err
}

// loadCpuObjects loads cpu and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cpuObjects
//	*cpuPrograms
//	*cpuMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCpuObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCpu()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cpuSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuSpecs struct {
	cpuProgramSpecs
	cpuMapSpecs
}

// cpuSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuProgramSpecs struct {
	TracepointSchedSwitch *ebpf.ProgramSpec `ebpf:"tracepoint_sched_switch"`
}

// cpuMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuMapSpecs struct {
	CpuStats *ebpf.MapSpec `ebpf:"cpu_stats"`
}

// cpuObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuObjects struct {
	cpuPrograms
	cpuMaps
}

func (o *cpuObjects) Close() error {
	return _CpuClose(
		&o.cpuPrograms,
		&o.cpuMaps,
	)
}

// cpuMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuMaps struct {
	CpuStats *ebpf.Map `ebpf:"cpu_stats"`
}

func (m *cpuMaps) Close() error {
	return _CpuClose(
		m.CpuStats,
	)
}

// cpuPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuPrograms struct {
	TracepointSchedSwitch *ebpf.Program `ebpf:"tracepoint_sched_switch"`
}

func (p *cpuPrograms) Close() error {
	return _CpuClose(
		p.TracepointSchedSwitch,
	)
}

func _CpuClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cpu_bpfel.o
var _CpuBytes []byte
